# Site settings
title:          Log-Press
description:    이슬찬의 글 보관함
url:            "https://2zzanii.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         슬찬
  url:          
  email:        tmfcks0215@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       7

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
